development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: solaro_innodb
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: solaro_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: solaro_test
  pool: 5
  username: root
  password:

cucumber:
  adapter: mysql2
  encoding: latin1
  reconnect: false
  database: solaro_test
  pool: 5
  username: root
  password:

staging:
  adapter: mysql2
  encoding: latin1
  reconnect: false
  database: solaro_test
  pool: 5
  username: root
  password: 
